### ISSUE TITLE
Running the app on localhost

### ISSUE THREAD

**Issue by iteimouri** [flaviagiammarino/dash-clustering#1]
Very interesting app! I'm trying to run it on conda virtual environment. To do so I do the following: 

`conda activate P:\myPythonEnv`

then navigate to the app directory: 

`cd P:\Documents\dash-clustering`

then I point to the application as: 

`set FLASK_APP = application`

which is the `application.py`

and finally `flask run` 

for which I get: 

`Error: Could not locate Flask application. You did not provide the FLASK_APP environment variable.`

I clearly declared `set FLASK_APP = application` so I wonder if there is something missing? 

python version: 3.9.7
flask version: 2.0.2

**Comment by flaviagiammarino** [comment]
Try
```
export FLASK_APP=application.py
flask run
```

**Comment by iteimouri** [comment]
I am running this on Windows, anaconda prompt (base), on windows CMS the command is set rather than export. Export is for the bash (see: https://flask.palletsprojects.com/en/2.0.x/cli/)

**Comment by flaviagiammarino** [comment]
I'm on Mac OS so I can't reproduce, it works fine for me.

**Comment by iteimouri** [comment]
I've managed to run it. One should use `python application.py` once the virtual env is running properly. Also changed a couple of things in the imports as they were depreciated.
